package no.nav.dokdistkanal.consumer.dki;

import no.nav.dokdistkanal.consumer.dki.to.DigitalKontaktinfoMapper;
import no.nav.dokdistkanal.consumer.dki.to.DigitalKontaktinformasjonTo;
import no.nav.dokdistkanal.consumer.dki.to.PostPersonerResponse;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;


@ExtendWith(MockitoExtension.class)
public class MapDigitalKontaktinformasjonTest {

	private static final String EPOSTADRESSE = "epostadresse";
	private static final String MOBILTELEFONNUMMER = "mobiltelefonnummer";
	private static final String LEVERANDORADRESSE = "leverandøradresse";
	private static final String BRUKERADRESSE = "brukeradresse";
	// Dette er et selvsignert X.509 sertifikat som er gyldig til 2033-03-04. Det er ment å emulere et sertifikat utstedt av postkasseleverandør for bruker
    // Generert med følgende kommando: openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout itest.key -out itest.pem
	private static final String LEVERANDOER_SERTIFIKAT_GYLDIG = "MIIELTCCAxWgAwIBAgIUNRGHPeWMlznfAYPk4OS4Lno0yCEwDQYJKoZIhvcNAQELBQAwgaUxCzAJBgNVBAYTAk5PMQ0wCwYDVQQIDARPc2xvMRMwEQYDVQQHDApCYWRlYmFra2VuMQwwCgYDVQQKDANOQVYxHTAbBgNVBAsMFERva3VtZW50bMODwrhzbmluZ2VyMRswGQYDVQQDDBJpdGVzdC1kb2tkaXN0a2FuYWwxKDAmBgkqhkiG9w0BCQEWGWl0ZXN0LWRva2Rpc3RrYW5hbEBuYXYubm8wHhcNMjMwMzA3MTAxMzU3WhcNMzMwMzA0MTAxMzU3WjCBpTELMAkGA1UEBhMCTk8xDTALBgNVBAgMBE9zbG8xEzARBgNVBAcMCkJhZGViYWtrZW4xDDAKBgNVBAoMA05BVjEdMBsGA1UECwwURG9rdW1lbnRsw4PCuHNuaW5nZXIxGzAZBgNVBAMMEml0ZXN0LWRva2Rpc3RrYW5hbDEoMCYGCSqGSIb3DQEJARYZaXRlc3QtZG9rZGlzdGthbmFsQG5hdi5ubzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK6K02dqev/lxVY34Q9ZnJR7I68BJdgYJ8phLzVglTtK0LrOlo+3A+6RmlZhZGq8dqcDBFnQF7x8KWgHaEtVTNLCJUFtuhraxpTuZBStyEugsbKhD45lcs+FlEQwHl6V61ljopl361yvZxVFRpJceGhJiyYh71di/JO/ke18ZZ3XOp8uPEhPM7Agswc69gx5yULWndzhopabo8TEN1sLIuavxWsAhbFZ1rukYG25R5q2dPsEIDtHvYHeJ8BohdcBv9dSNFD/Rrt8sVafmfwazFX2Q9UL09e/WI9BeefN6ffQ5hPkAIa7hrGnaOTW+qcMXCaUQXjJH9t9I+9eDBfTjcUCAwEAAaNTMFEwHQYDVR0OBBYEFFlQrX4esHWZp4RZGA2dof85V6UfMB8GA1UdIwQYMBaAFFlQrX4esHWZp4RZGA2dof85V6UfMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC+b+iPtjCqWoRfjBRpuOe4ZKkRIIsO9t0cB+TKKnlfj64T43unl9PKgTCHhZlrFWMrpGN6BV6Mk9xoWvsZUIOGdbESblCqseeW52hYD1S6k6MCmHctHyDO4DrBHimPmRFkLJyS8dKm6kBj2JcNFPb4GCHgnHpZY8eWoYqJBwOFy1YD3Xp+GvpZLJP8yTF0wlYIDwNwgS3wFtD0wPPio4tiS4ad1ywUuwvHIsdaj/lHS9FzIvmoUx4YUJ1mIhGQfMhKzOJy38VIGqBT5U+zCUcUXyRONaV2Iyb2xKC8qHdTX9/Y1fwNOqaAdqD2HZ8T/pg4PYKW4iupoUIfvtrnZoUg=";
	private static final String LEVERANDOER_SERTIFIKAT_UGYLDIG = "MIIE+TCCA+GgAwIBAgILAUhKqNpiy3zXb/YwDQYJKoZIhvcNAQELBQAwUTELMAkGA1UEBhMCTk8xHTAbBgNVBAoMFEJ1eXBhc3MgQVMtOTgzMTYzMzI3MSMwIQYDVQQDDBpCdXlwYXNzIENsYXNzIDMgVGVzdDQgQ0EgMzAeFw0xNzA2MDkxMzQyMTFaFw0yMDA2MTIyMTU5MDBaMF8xCzAJBgNVBAYTAk5PMRIwEAYDVQQKDAlFLUJPS1MgQVMxFDASBgNVBAsMC09wZXJhdGlvbiAxMRIwEAYDVQQDDAlFLUJPS1MgQVMxEjAQBgNVBAUTCTk5NjQ2MDMyMDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJhF7jKFz1H5mfm2NO5jcVOsHGe6etEcBZzTlbKbqzarkcsBW5Xf7/DCcxtzzkUQyiO9yxhAdg6uIpmStlruZcntLtIvZpsWrV60D4gJAUzyHcynxedKoGjUob5qQ6FIlAaqxMZ4kGQvHbzYJ1N9OMWGISENUP4JPYkojFEHwRswORrvmWglj3RU4QbO4Ggg1pvrEddoEafsgnLZOKxz1DSAKwLbv2y0FNhs3akSozbuWC+tmnMNi6y8ufZnrHo099Tl3Uj37EzPY6g1qqqdDEKEhGrrrMzNvf1muGcChWKnDffUuWS4i8MH2tP1raO8dl4vjIkM8Uh9E9Z/hY134OUCAwEAAaOCAcIwggG+MAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUP671eAuSo3AgNV9a+vckoFIB8EEwHQYDVR0OBBYEFGFGK3fHTWkdBSvGz+SuZVl3rESFMA4GA1UdDwEB/wQEAwIEsDAWBgNVHSAEDzANMAsGCWCEQgEaAQADAjCBuwYDVR0fBIGzMIGwMDegNaAzhjFodHRwOi8vY3JsLnRlc3Q0LmJ1eXBhc3Mubm8vY3JsL0JQQ2xhc3MzVDRDQTMuY3JsMHWgc6Bxhm9sZGFwOi8vbGRhcC50ZXN0NC5idXlwYXNzLm5vL2RjPUJ1eXBhc3MsZGM9Tk8sQ049QnV5cGFzcyUyMENsYXNzJTIwMyUyMFRlc3Q0JTIwQ0ElMjAzP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwgYoGCCsGAQUFBwEBBH4wfDA7BggrBgEFBQcwAYYvaHR0cDovL29jc3AudGVzdDQuYnV5cGFzcy5uby9vY3NwL0JQQ2xhc3MzVDRDQTMwPQYIKwYBBQUHMAKGMWh0dHA6Ly9jcnQudGVzdDQuYnV5cGFzcy5uby9jcnQvQlBDbGFzczNUNENBMy5jZXIwDQYJKoZIhvcNAQELBQADggEBAElnmjuY+gPxzLVsjqGAbW0fEZXhbYRaQKS/65+6Gh0STfArBma62CdIvgq5JQMmr47URdkxDhB12SYaMHUyOee9+d3hTpmvplxd4xz/gqSisHJq5wNZfgtf5y4vtxM4X1LNrf93i6plNWpesWWznON8MWRvmm+K+3uSC6trD0o5dv6ax/cuCffgGP4qJ9z59qKFDZrNNEfA1In3ij6V3Gebo7oSJxSlR5enOJTxJOjO2De5k1ObQvPAD9yc2a+eWgkMygsBT3ay5BKCtQcSHfJm3CRNN6bfD3D4kxP3ZvAirvKADcUlS71FAnWqPPoXgxiSJGMPkwjuZJsQeeVd5JA=";
	private static final boolean KAN_VARSLES_TRUE = true;
	private static final boolean KAN_VARSLES_FALSE = false;
	private static final boolean RESERVERT = false;

	private final DigitalKontaktinfoMapper digitalKontaktinfoMapper = new DigitalKontaktinfoMapper();

	@Test
	public void shouldMapOk() {
		DigitalKontaktinformasjonTo digitalKontaktinformasjonTo = digitalKontaktinfoMapper.mapDigitalKontaktinformasjon(createDigitalKontaktinfo(KAN_VARSLES_TRUE, LEVERANDOER_SERTIFIKAT_GYLDIG));
		assertEquals(BRUKERADRESSE, digitalKontaktinformasjonTo.getBrukerAdresse());
		assertEquals(EPOSTADRESSE, digitalKontaktinformasjonTo.getEpostadresse());
		assertEquals(LEVERANDORADRESSE, digitalKontaktinformasjonTo.getLeverandoerAdresse());
		assertEquals(MOBILTELEFONNUMMER, digitalKontaktinformasjonTo.getMobiltelefonnummer());
		assertTrue(digitalKontaktinformasjonTo.isGyldigSertifikat());
	}

	@Test
	public void shouldMapWithoutKanVarsles() {
		DigitalKontaktinformasjonTo digitalKontaktinformasjonTo = digitalKontaktinfoMapper.mapDigitalKontaktinformasjon(createDigitalKontaktinfo(KAN_VARSLES_FALSE, LEVERANDOER_SERTIFIKAT_GYLDIG));
		assertEquals(BRUKERADRESSE, digitalKontaktinformasjonTo.getBrukerAdresse());
		assertEquals(LEVERANDORADRESSE, digitalKontaktinformasjonTo.getLeverandoerAdresse());
		assertNull(digitalKontaktinformasjonTo.getEpostadresse());
		assertNull(digitalKontaktinformasjonTo.getMobiltelefonnummer());
	}

	@Test
	public void shouldMapWithoutGyldigSertifikat() {
		DigitalKontaktinformasjonTo digitalKontaktinformasjonTo = digitalKontaktinfoMapper.mapDigitalKontaktinformasjon(createDigitalKontaktinfo(KAN_VARSLES_TRUE, LEVERANDOER_SERTIFIKAT_UGYLDIG));
		assertEquals(BRUKERADRESSE, digitalKontaktinformasjonTo.getBrukerAdresse());
		assertEquals(EPOSTADRESSE, digitalKontaktinformasjonTo.getEpostadresse());
		assertEquals(LEVERANDORADRESSE, digitalKontaktinformasjonTo.getLeverandoerAdresse());
		assertEquals(MOBILTELEFONNUMMER, digitalKontaktinformasjonTo.getMobiltelefonnummer());
		assertFalse(digitalKontaktinformasjonTo.isGyldigSertifikat());
	}

	private PostPersonerResponse.DigitalKontaktinfo createDigitalKontaktinfo(boolean kanVarsles, String leverandoerSertifikat) {
		return PostPersonerResponse.DigitalKontaktinfo.builder()
				.epostadresse(EPOSTADRESSE)
				.mobiltelefonnummer(MOBILTELEFONNUMMER)
				.kanVarsles(kanVarsles)
				.reservert(RESERVERT)
				.sikkerDigitalPostkasse(PostPersonerResponse.SikkerDigitalPostkasse.builder()
						.adresse(BRUKERADRESSE)
						.leverandoerAdresse(LEVERANDORADRESSE)
						.leverandoerSertifikat(leverandoerSertifikat)
						.build())
				.build();
	}
}
