kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DOKUMENTTYPEINFO_URL
      value: {{ DOKUMENTTYPEINFO_URL }}
    - name: DOKDISTKANAL_ENHETSREGISTER_URL
      value: {{ DOKDISTKANAL_ENHETSREGISTER_URL }}
    - name: DOKDISTKANAL_ALTINN_URL
      value: {{ DOKDISTKANAL_ALTINN_URL }}
    - name: DOKDISTKANAL_ENDPOINTS_DIGDIR_KRR_PROXY_URL
      value: {{ DOKDISTKANAL_ENDPOINTS_DIGDIR_KRR_PROXY_URL }}
    - name: DOKDISTKANAL_ENDPOINTS_DIGDIR_KRR_PROXY_SCOPE
      value: {{ DOKDISTKANAL_ENDPOINTS_DIGDIR_KRR_PROXY_SCOPE }}
    - name: DOKDISTKANAL_ENDPOINTS_PDL_URL
      value: {{ DOKDISTKANAL_ENDPOINTS_PDL_URL }}
    - name: DOKDISTKANAL_ENDPOINTS_PDL_SCOPE
      value: {{ DOKDISTKANAL_ENDPOINTS_PDL_SCOPE }}
    - name: DOKDISTKANAL_ENDPOINTS_DOKMET_URL
      value: {{ DOKDISTKANAL_ENDPOINTS_DOKMET_URL }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
           {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 20m
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: altinn:serviceowner/notifications.read
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
  envFrom:
    - secret: {{ DOKDISTKANAL_SECRETS }}
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
       - application: {{app}}
         namespace: {{namespace}}
         cluster: {{cluster}}
    {{/each}}

